/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

import Config.Session;
import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author USER27
 */
public class StudentDashboard extends javax.swing.JFrame {

    /**
     * Creates new form teacherDashboard
     */
    public StudentDashboard() {
    if (Config.Session.userId == 0) {
        javax.swing.JOptionPane.showMessageDialog(null, "Login Required! Redirecting...");
        new Main.Login().setVisible(true);
        this.dispose();
        return;
    }
    
    initComponents();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Home1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        item = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        Profile1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        setting = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        searchField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        logoutBtn = new javax.swing.JPanel();
        jLabel8logout = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Colonna MT", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LOST AND FOUND HUB");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 970, 110));

        Home1.setBackground(new java.awt.Color(102, 102, 102));
        Home1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Home1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Home1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Home1MouseExited(evt);
            }
        });
        Home1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Colonna MT", 1, 36)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Home");
        Home1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 220, 70));

        jPanel1.add(Home1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 250, 90));

        item.setBackground(new java.awt.Color(102, 102, 102));
        item.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        item.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                itemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                itemMouseExited(evt);
            }
        });
        item.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Colonna MT", 1, 36)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Item");
        item.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 3, 240, 70));

        jPanel1.add(item, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 250, 80));

        Profile1.setBackground(new java.awt.Color(102, 102, 102));
        Profile1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Profile1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Profile1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Profile1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Profile1MouseExited(evt);
            }
        });
        Profile1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Colonna MT", 1, 36)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Profile");
        Profile1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 4, 250, 80));

        jPanel1.add(Profile1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 250, 90));

        setting.setBackground(new java.awt.Color(102, 102, 102));
        setting.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                settingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                settingMouseExited(evt);
            }
        });
        setting.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Colonna MT", 1, 36)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Setting");
        setting.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, -1, 250, 80));

        jPanel1.add(setting, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 250, 80));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        searchField.setForeground(new java.awt.Color(153, 153, 153));
        searchField.setText("  Search...");
        searchField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchFieldFocusLost(evt);
            }
        });
        searchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFieldActionPerformed(evt);
            }
        });
        searchField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchFieldKeyReleased(evt);
            }
        });
        jPanel3.add(searchField, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 10, 210, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 990, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/test3.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 220, -1, -1));

        logoutBtn.setBackground(new java.awt.Color(102, 102, 102));
        logoutBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        logoutBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutBtnMouseExited(evt);
            }
        });
        logoutBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8logout.setFont(new java.awt.Font("Colonna MT", 1, 36)); // NOI18N
        jLabel8logout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8logout.setText("Logout");
        logoutBtn.add(jLabel8logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -1, 250, 80));

        jPanel1.add(logoutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 250, 80));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/background 2.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-180, 180, 1170, 460));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -21, 964, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void setColor(javax.swing.JPanel p){
        p.setBackground(new java.awt.Color(240, 240, 240));
    }
    
    public void resetColor(javax.swing.JPanel p2){
        p2.setBackground(new java.awt.Color(102, 102, 102));
    }
    private void Home1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Home1MouseEntered
        setColor(Home1);
    }//GEN-LAST:event_Home1MouseEntered

    private void Home1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Home1MouseExited
        resetColor(Home1);
    }//GEN-LAST:event_Home1MouseExited

    private void itemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemMouseClicked
                                         
        // This opens the Item list (which we just updated to show tbl_items)
        Item itemFrame = new Item(); 
        itemFrame.setVisible(true);
        this.dispose(); // Closes the Dashboard
    
    }//GEN-LAST:event_itemMouseClicked

    private void itemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemMouseEntered
        setColor(item);
    }//GEN-LAST:event_itemMouseEntered

    private void itemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemMouseExited
        resetColor(item);
    }//GEN-LAST:event_itemMouseExited

    private void Profile1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Profile1MouseClicked
        profile prof = new profile(Session.userId);
        prof.setVisible(true);
        dispose();
    }//GEN-LAST:event_Profile1MouseClicked

    private void Profile1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Profile1MouseEntered
        setColor(Profile1);
    }//GEN-LAST:event_Profile1MouseEntered

    private void Profile1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Profile1MouseExited
        resetColor(Profile1);
    }//GEN-LAST:event_Profile1MouseExited

    private void settingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingMouseEntered
        setColor(setting);
    }//GEN-LAST:event_settingMouseEntered

    private void settingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingMouseExited
        resetColor(setting);
    }//GEN-LAST:event_settingMouseExited

    private void searchFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchFieldFocusGained
        if (searchField.getText().equals("Search...")) {
            searchField.setText("");
            searchField.setForeground(java.awt.Color.BLACK);
        }
    }//GEN-LAST:event_searchFieldFocusGained

    private void searchFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchFieldFocusLost
        if (searchField.getText().isEmpty()) {
            searchField.setForeground(java.awt.Color.GRAY);
            searchField.setText("Search...");
        }
    }//GEN-LAST:event_searchFieldFocusLost

    private void searchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchFieldActionPerformed

    private void searchFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchFieldKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_searchFieldKeyReleased

    private void logoutBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutBtnMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutBtnMouseExited

    private void logoutBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutBtnMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutBtnMouseEntered

    private void logoutBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutBtnMouseClicked

        // 1. Ask for confirmation (Optional but highly recommended)
        int confirm = javax.swing.JOptionPane.showConfirmDialog(null,
            "Are you sure you want to logout?", "Logout",
            javax.swing.JOptionPane.YES_NO_OPTION);

        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            // 2. Clear the Session (Reset to 0)
            Config.Session.userId = 0;

            // 3. Open Login Frame
            Main.Login login = new Main.Login();
            login.setVisible(true);

            // 4. Close the Dashboard
            this.dispose();
        }
    }//GEN-LAST:event_logoutBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Home1;
    private javax.swing.JPanel Profile1;
    private javax.swing.JPanel item;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel8logout;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel logoutBtn;
    private javax.swing.JTextField searchField;
    private javax.swing.JPanel setting;
    // End of variables declaration//GEN-END:variables
}
